/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.JTable;
import static comidaapp.ComidaApp.tablaGlobal;
import comidaapp.ModelView.Comida;
import comidaapp.ModelView.FirebaseSaveObject;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro Padilla
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    
    private ListSelectionListener tableSelectionListener;
    
    public Inventario() {
        initComponents();
    }
    
    public Comida regisAnimalTab(){
        Comida anim1 = new Comida(txtAlimento.getText(),txtTipAli.getText(),TxtCantidad.getText());
        return anim1;
    }
    
    public void ModificarCeldas(String[] Fila){
        txtAlimento.setText(Fila[0]);
        txtTipAli.setText(Fila[1]);
        TxtCantidad.setText(Fila[2]);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Butsalir = new javax.swing.JButton();
        Butordenar = new javax.swing.JButton();
        txtAlimento = new javax.swing.JTextField();
        txtTipAli = new javax.swing.JTextField();
        TxtCantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Tipo Alimento", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Butsalir.setText("Regresar");
        Butsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButsalirActionPerformed(evt);
            }
        });

        Butordenar.setText("Ordenar ");
        Butordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButordenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(Butsalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Butordenar, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(txtAlimento)
                            .addComponent(txtTipAli)
                            .addComponent(TxtCantidad))))
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(txtAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txtTipAli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(Butordenar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Butsalir)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButsalirActionPerformed
       MenuMain menu = new MenuMain();
       menu.setVisible(true);
       menu.setLocationRelativeTo(null);
       dispose();
    }//GEN-LAST:event_ButsalirActionPerformed

    private void ButordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButordenarActionPerformed
        try {
            if (regisAnimalTab().getAlimento().equals(ordenar()[0])){
                if (Integer.parseInt(regisAnimalTab().getCantidadAlimento()) > 0){
                    TxtCantidad.setText(ordenar()[2]);
                    FirebaseSaveObject.conexionglobal.saveFree(regisAnimalTab(),regisAnimalTab().getAlimento());
                    JOptionPane.showMessageDialog(this, "Se Tomo el pedido correctamente");
                } 
                else{
                    JOptionPane.showMessageDialog(this, "No hay existencias e el inventario");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "No hay existencias en el inventario ");
            }
        } 
        catch (FileNotFoundException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        };
        comidaapp.ComidaApp.tablaGlobal.dispose();
        FirebaseSaveObject.conexionglobal.showDataInJTable(comidaapp.ComidaApp.tablaGlobal.getjTable1());
        comidaapp.ComidaApp.tablaGlobal.setVisible(true);
        comidaapp.ComidaApp.tablaGlobal.setLocationRelativeTo(null);
    }//GEN-LAST:event_ButordenarActionPerformed

    /**
     */
    public void initTableSelectionModel() {
        ListSelectionModel selectionModel = comidaapp.ComidaApp.tablaGlobal.getjTable1().getSelectionModel();
        tableSelectionListener = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedIndex = comidaapp.ComidaApp.tablaGlobal.getjTable1().getSelectedRow() ;
                    if (selectedIndex != -1) {
                        ModificarCeldas(getSelectedRowData(comidaapp.ComidaApp.tablaGlobal.getjTable1()));
                    }
                }
            }
        };    
        selectionModel.addListSelectionListener(tableSelectionListener);
    }
    
    public String[] getSelectedRowData(JTable tabla) {
        int selectedIndex = tabla.getSelectedRow();
        if (selectedIndex != -1) {
            int columnCount = tabla.getColumnCount();
            String[] Fila = new String[columnCount];
            for (int i = 0; i < columnCount; i++) {
                Fila[i] = (String) tabla.getValueAt(selectedIndex, i);
            }
            return Fila;
        } else {
            return null;
        }
    }
    
    // Metodo que muestra la informacion en los JTextFields
    
    public String[] ordenar(){  
        String[] fila = getSelectedRowData(comidaapp.ComidaApp.tablaGlobal.getjTable1());
        int inventario = Integer.parseInt(fila[2]);
        if (inventario > 0){
            int nwinvent = (inventario - 1);
            String newinventario = Integer.toString(nwinvent);
            fila[2] = newinventario;
            return fila;
        }
        else {
            return fila;
        }
    }
    
    public JTable getjTable1() {
        return jTable1;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Butordenar;
    private javax.swing.JButton Butsalir;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAlimento;
    private javax.swing.JTextField txtTipAli;
    // End of variables declaration//GEN-END:variables
}
